// Generates netlify/functions/_agent.mjs from agent/*.ps1 (run: node build.mjs)
import { readFileSync, writeFileSync } from 'node:fs';
const agent = readFileSync('agent/agent.ps1', 'utf8').replace(/\r\n/g, '\n');
const install = readFileSync('agent/install.ps1', 'utf8').replace(/\r\n/g, '\n');
if (/^'@/m.test(agent)) throw new Error("agent.ps1 must not contain a line starting with '@");
if (/[^\x00-\x7f]/.test(agent + install)) throw new Error('agent scripts must be ASCII only');
const out = `// GENERATED by build.mjs from agent/*.ps1. Do not edit.
const AGENT = ${JSON.stringify(agent)};
const INSTALL = ${JSON.stringify(install)};
export function agentTemplate(server, token, uninstall) {
  const payload = INSTALL.split('__AGENT__').join(AGENT)
    .split('__SERVER__').join(server).split('__TOKEN__').join(token)
    .split('__MODE__').join(uninstall ? 'uninstall' : 'install');
  const head = [
    '@echo off',
    'setlocal',
    'set "RK_SELF=%~f0"',
    'title RANKED',
    'powershell -NoProfile -ExecutionPolicy Bypass -Command "$c=[IO.File]::ReadAllText($env:RK_SELF); $i=$c.IndexOf(\\'#RK\\'+\\'PAYLOAD\\'); Invoke-Expression $c.Substring($i)"',
    'echo.',
    'pause',
    'exit /b',
    '#RKPAYLOAD',
  ].join('\\r\\n');
  return head + '\\r\\n' + payload.replace(/\\n/g, '\\r\\n');
}
`;
writeFileSync('netlify/functions/_agent.mjs', out);
console.log('ok _agent.mjs', out.length, 'bytes');
